### ISSUE TITLE
Error: Module version mismatch. Expected 49, got 48

### ISSUE THREAD

**Issue by wilsonpage** [don/node-eddystone-beacon#40]
I'm getting the following ambiguous error:

``` bash
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wilsonpage/Documents/m/mozilla-magnet/magnet-client-desktop/node_modules/xpc-connection/index.js:3:15)
```

**Comment by wilsonpage** [comment]
- When run via Electron
- Node v6.3.0

**Comment by wilsonpage** [comment]
I used [`electron-rebuild`](https://github.com/electron/electron-rebuild) which seemed to fix my issue 😄

**Comment by shankarsengalani** [comment]
Hey @wilsonpage, I too have the same issue and by running `./node_modules/.bin/electron-rebuild` in my root folder where I have my `node_modules` doesn't seems work.

**Comment by wilsonpage** [comment]
I can't suggest anything really, this is all voodoo magic to me 🔥

**Comment by baboundu81** [comment]
Hi ! I have the same issue on mac, but not on windows :
- node v6.3.1
- npm v3.10.3
- electron v1.3.2

electron-rebuild doesn't work either for me. @shankar2105 Did you found out how to fix the bug ?

**Comment by baboundu81** [comment]
In case anybody had the same issue, I finally fixed it, I forgot to set the environment variables for electron-rebuild script as mentioned [here](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md).

**Comment by sandover** [comment]
Not sure I understand your resolution -- the section on `electron-rebuild` doesn't mention needing or using environment variables.

**Comment by vohtaski** [comment]
@sandover
I had a similar problem. The version of electron in the link above is `npm_config_target=1.2.3`
my electron had `1.4.5`. As soon I fixed it in the script, the error disappeared..
